#-----------------------------
# Data loader section args
#-----------------------------
data_loader:
  name: imagenet
  root: "../../../.dataset"
  split: "train"
  batch_size: 64
  shuffle: True
  num_workers: 0
  is_download: True
  is_load_train_set: True
  is_load_test_set: True
  task_type: cv
