#-----------------------------
# Data loader section args
#-----------------------------
data_loader:
  name: yahooanswers
  root: "../../../.dataset"
  split: ""
  batch_size: 64
  shuffle: True
  num_workers: 0
  is_download: True
  is_load_train_set: True
  is_load_test_set: True
  task_type: nlp
  vocab_size: None
