#-----------------------------
# Optimizer section args
#-----------------------------
optimizer:
  type: RMSprop
  lr: 0.01
  alpha: 0.99
  eps: 1e-8
  weight_decay: 0.0
  momentum: 0.0
  centered: False
