name: Mirror to dev repo

on:
  push:
    branches: [ "main" ]     
  workflow_dispatch:          
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up git identity
        run: |
          git config user.name "shuaijunchenex"
          git config user.email "46318558+shuaijunchenex@users.noreply.github.com"

      - name: Push main to dev repo
        env:
          TOKEN: ${{secrets.CAPSTONE_ACCESS_TOKEN}}
        run: |
          git remote add dev https://${TOKEN}@github.com/shuaijunchenex/usyd-learning-dev.git
          git push dev main:main --force-with-lease
