name: Mirror to dev repo (exclude .github, force push to main)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1) 检出完整历史（避免 index-pack 问题）
      - name: Checkout (no default creds, full history)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2) 设置一次 Git 身份用于临时提交
      - name: Set up git identity
        run: |
          git config user.name "shuaijunchenex"
          git config user.email "46318558+shuaijunchenex@users.noreply.github.com"

      # 3) 在临时分支里删除 .github 并提交（不影响 A 的远端）
      - name: Build filtered branch (exclude .github)
        run: |
          set -e
          git checkout -b sync-excluding-dotgithub
          rm -rf .github
          git add -A
          git commit -m "Sync: exclude .github directory" || echo "No changes to commit"

      # 4) 强制推送到目标仓库 B 的 main
      - name: Force push to target main
        env:
          TOKEN: ${{ secrets.CAPSTONE_PUSH_TOKEN }}
        run: |
          set -e
          git remote remove dev 2>/dev/null || true
          git remote add dev https://github.com/shuaijunchenex/usyd-learning-dev.git

          # 稳定性配置
          git config --global http.version HTTP/1.1
          git config --global core.compression 0
          git config --global credential.helper ""
          export GIT_ASKPASS=/bin/true

          # 使用 Basic Auth 头（推荐，不把 token 暴露在 URL）
          AUTH=$(printf "%s" "x-access-token:${TOKEN}" | base64 | tr -d '\n')

          # 强制推送到 B 的 main
          git -c http.extraheader="Authorization: Basic ${AUTH}" \
              push dev HEAD:main --force
