name: Mirror to dev repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no default creds)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up git identity
        run: |
          git config user.name "shuaijunchenex"
          git config user.email "46318558+shuaijunchenex@users.noreply.github.com"

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Try pushing to a new branch (write test)
        env:
          TOKEN: ${{ secrets.CAPSTONE_PUSH_TOKEN }}
        run: |
          set -e
          git remote remove dev 2>/dev/null || true
          git remote add dev https://github.com/shuaijunchenex/usyd-learning-dev.git

          # 稳定性（可留着）
          git config --global http.version HTTP/1.1
          git config --global core.compression 0
          git config --global credential.helper ""
          export GIT_ASKPASS=/bin/true

          AUTH=$(printf "%s" "x-access-token:${TOKEN}" | base64 | tr -d '\n')

          git checkout -b can-push-test
          git commit --allow-empty -m "perm test"

          git -c http.extraheader="Authorization: Basic ${AUTH}" \
              push dev HEAD:can-push-test -v






      # - name: Sanity check token can read target repo
      #   env:
      #     TOKEN: ${{ secrets.CAPSTONE_ACCESS_TOKEN }}
      #   run: |
      #     git ls-remote https://x-access-token:${TOKEN}@github.com/shuaijunchenex/usyd-learning-dev.git HEAD


      # - name: Push main to dev repo
      #   env:
      #     TOKEN: ${{ secrets.CAPSTONE_ACCESS_TOKEN }}
      #   run: |
      #     # 关键：用户名用 x-access-token
      #     git remote add dev https://x-access-token:${TOKEN}@github.com/shuaijunchenex/usyd-learning-dev.git
      #     git push dev main:main --force-with-lease